LibaryPrograming/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibaryPrograming.Models.Entity;
namespace LibaryPrograming.Controllers
{
    public class KitapController : Controller
    {
        // GET: Urun
        KutuphaneDbEntities db = new KutuphaneDbEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLKITAPLARs.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult KıtapEkle()
        {
            List<SelectListItem> degerler = (from i in db.TBLKATEGORIs.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            List<SelectListItem> degerler2 = (from i in db.TBLYAZARs.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.YAZARAD,
                                                 Value = i.YAZARID.ToString()
                                             }).ToList();
            ViewBag.dgr2 = degerler2;
            return View();
        }
        [HttpPost]
        public ActionResult KıtapEkle(TBLKITAPLAR p1)
        {
            var ktg = db.TBLKATEGORIs.Where(m => m.KATEGORIID == p1.TBLKATEGORI.KATEGORIID).FirstOrDefault();
            p1.TBLKATEGORI = ktg;
            var ktg2 = db.TBLYAZARs.Where(m => m.YAZARID == p1.TBLYAZAR.YAZARID).FirstOrDefault();
            p1.TBLYAZAR = ktg2;
            db.TBLKITAPLARs.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SIL(int id)
        {
            var kıtap = db.TBLKITAPLARs.Find(id);
            db.TBLKITAPLARs.Remove(kıtap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KitapGetir(int id)
        {
            var ktp = db.TBLKITAPLARs.Find(id);

            List<SelectListItem> degerler = (from i in db.TBLKATEGORIs.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            List<SelectListItem> degerler2 = (from i in db.TBLYAZARs.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = i.YAZARAD,
                                                  Value = i.YAZARID.ToString()
                                              }).ToList();
            ViewBag.dgr2 = degerler2;
            return View("KitapGetir", ktp);
        }
        public ActionResult Guncelle(TBLKITAPLAR p)
        {
            var ktp = db.TBLKITAPLARs.Find(p.KITAPID);
            ktp.KITAPAD = p.KITAPAD;
            ktp.ADET = p.ADET;
            //ktp.KITAPKATEGORİ = p.KITAPKATEGORİ;
            //ktp.KİTAPYAZAR = p.KİTAPYAZAR;
            var ktg = db.TBLKATEGORIs.Where(m => m.KATEGORIID == p.TBLKATEGORI.KATEGORIID).FirstOrDefault();
            ktp.KITAPKATEGORİ = ktg.KATEGORIID;
            var ktg2 = db.TBLYAZARs.Where(m => m.YAZARID == p.TBLYAZAR.YAZARID).FirstOrDefault();
            ktp.KİTAPYAZAR = ktg2.YAZARID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

LibaryPrograming/Views/Kitap/Index.cshtml
@using LibaryPrograming.Models.Entity
@model List<TBLKITAPLAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>KİTAP ID</th>
            <th>KİTAP ADI</th>
            <th>KATEGORİ</th>
            <th>YAZAR</th>
            <th>ADET</th>
            <th>SİL</th>
            <th>GUNCELLE</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var ktp in Model)
        {
            <tr>
                <th>@ktp.KITAPID</th>
                <td>@ktp.KITAPAD</td>
                <td>@ktp.TBLKATEGORI.KATEGORIAD</td>
                <td>@ktp.TBLYAZAR.YAZARAD</td>
                <td>@ktp.ADET</td>
                <td><a href="/KITAP/SIL/@ktp.KITAPID" class="btn btn-danger  ">SİL</a></td>
                <td><a href="/KITAP/KitapGetir/@ktp.KITAPID" class="btn btn-success">GÜNCELLE</a></td>
            </tr>
        }
    </tbody>
</table>
<a href="/KITAP/KıtapEkle/" class="btn btn-primary">YENİ KITAP EKLE</a>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />
<script>
    $('#tbl1').dataTable();
</script>

LibaryPrograming/Views/Kitap/KitapGetir.cshtml
@model LibaryPrograming.Models.Entity.TBLKITAPLAR
@{
    ViewBag.Title = "KitapGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Kitap", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.KITAPID)
    @Html.TextBoxFor(m => m.KITAPID, new { @class = "form-kontrol" })
    <br /><br />
    @Html.LabelFor(m => m.KITAPAD)
    @Html.TextBoxFor(m => m.KITAPAD, new { @class = "form-kontrol" })
    <br /><br />
    @Html.LabelFor(m => m.KITAPKATEGORİ)
    @Html.DropDownListFor(m => m.TBLKATEGORI.KATEGORIID, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-kontrol" }))
    @*@Html.TextBoxFor(m => m.KITAPKATEGORİ, new { @class = "form-kontrol" })*@
    <br /><br />
    @Html.LabelFor(m => m.KİTAPYAZAR)
    @Html.DropDownListFor(m => m.TBLYAZAR.YAZARID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-kontrol" }))
    @*@Html.TextBoxFor(m => m.KİTAPYAZAR, new { @class = "form-kontrol" })*@
    <br /><br />
    @Html.LabelFor(m => m.ADET)
    @Html.TextBoxFor(m => m.ADET, new { @class = "form-kontrol" })

</div>
    <div>
        <button class="btn btn-warning">Kitap Güncelle</button>
    </div>
}

LibaryPrograming/Views/Kitap/KıtapEkle.cshtml
@model  LibaryPrograming.Models.Entity.TBLKITAPLAR
@{
    ViewBag.Title = "KıtapEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>Kitap Adı</label>
        <input type="text" class="form-control" name="KITAPAD" required="" maxlength="30" placeholder="Kıtap adı" />
    </div>
    <div>
        <label>Kitap Kategori</label>
        @Html.DropDownListFor(m => m.TBLKATEGORI.KATEGORIID, (List<SelectListItem>)ViewBag.dgr, new {@class="from-control"})
    </div>
    <div>
        <label>Yazar Adı</label>
       
        @Html.DropDownListFor(m => m.TBLYAZAR.YAZARID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "from-control" })
    </div>
    <div>
        <label>Adet Miktarı</label>
        <input type="text" class="form-control" name="KITAPADET"  placeholder="Kıtap adeti"  />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Kıtap Ekle</button>
    </div>
</form>