LibaryPrograming/Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibaryPrograming.Models.Entity;
namespace LibaryPrograming.Controllers
{
    public class UyeController : Controller
    {
        // GET: Uye
        KutuphaneDbEntities db = new KutuphaneDbEntities();

        public ActionResult Index(string p)
        {
            var degerler = from d in db.TBLUYEs select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.UYEAD.Contains(p));
            }
            return View(degerler.ToList());
            //var degerler = db.TBLUYEs.ToList();
            //return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniUye()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniUye(TBLUYE p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniUye");
            }
            db.TBLUYEs.Add(p1);
            db.SaveChanges();
            return View();
        }
        public ActionResult SIL(int id)
        {
            var uye = db.TBLUYEs.Find(id);
            db.TBLUYEs.Remove(uye);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UyeGetir(int id)
        {
            var uye = db.TBLUYEs.Find(id);
            return View("UyeGetir", uye);
        }
        public ActionResult Guncelle(TBLUYE p1)
        {
            var uye = db.TBLUYEs.Find(p1.UYEID);
            uye.UYEAD = p1.UYEAD;
            uye.UYESOYAD = p1.UYESOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

LibaryPrograming/Views/Uye/Index.cshtml
@using LibaryPrograming.Models.Entity
@model List<TBLUYE>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (Html.BeginForm("Index","Uye", FormMethod.Get))
            {
                <p>
                    Aranacak Uye Adı: @Html.TextBox("p")
                    <input type="submit" value="Ara" />
                </p>
            }


<table class="table table-bordered">
    <tr>
        <th>UYE ID</th>
        <th>UYE ADI</th>
        <th>UYE SOYADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>Alert</th>
    </tr>
    <tbody>
        @foreach (var uye in Model)
        {
        <tr>
            <th>@uye.UYEID</th>
            <th>@uye.UYEAD</th>
            <td>@uye.UYESOYAD</td>
            <td><a href="/UYE/SIL/@uye.UYEID" class="btn btn-danger  ">SİL</a></td>
            <td><a href="/UYE/UyeGetir/@uye.UYEID" class="btn btn-success">GÜNCELLE</a></td>
            <td>@Html.ActionLink("SİL BUTONU", "SIL", new {id=uye.UYEID} ,new
           {
               @class = "btn btn-warning",
               onclick = "return confirm('Gerçekten silmek istiyor musunuz?')"
           })
            </td>
        </tr>
        }
    </tbody>
</table>
<a href="/UYE/YeniUye/" class="btn btn-primary">YENİ UYE EKLE</a>

LibaryPrograming/Views/Uye/UyeGetir.cshtml
@model LibaryPrograming.Models.Entity.TBLUYE
@{
    ViewBag.Title = "UyeGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Uye", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.UYEID)
    @Html.TextBoxFor(m => m.UYEID, new { @class = "form-kontrol" })
    <br /><br />
    @Html.LabelFor(m => m.UYEAD)
    @Html.TextBoxFor(m => m.UYEAD, new { @class = "form-kontrol" })
    <br /><br />
    @Html.LabelFor(m => m.UYESOYAD)
    @Html.TextBoxFor(m => m.UYESOYAD, new { @class = "form-kontrol" })
</div>
    <div>
        <button class="btn btn-warning">Uye Güncelle</button>
    </div>
}

LibaryPrograming/Views/Uye/YeniUye.cshtml
@model LibaryPrograming.Models.Entity.TBLUYE
@{
    ViewBag.Title = "YeniUye";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>Uye Adı</label>
        @Html.TextBoxFor(m => m.UYEAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.UYEAD, "", new { @style = "color:green" })
    </div>
    <div>
        <label>Uye Soyadı</label>
        <input type="text" class="form-control" name="UYESOYAD" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="btn1">Uye Ekle</button>
    </div>
    <script>
        $('#btn1').click(function () {
            alert('Müsteri ekleme işlemi yapıldı...')
        });
    </script>
</form>